In [14]:
import tensorflow as tf
import numpy as np

In [3]:
tensor_0d = tf.constant(1)
print(tensor_0d)

tf.Tensor(1, shape=(), dtype=int32)


In [5]:
tensor_1d = tf.constant([1,5,6])
print(tensor_1d)

tf.Tensor([1 5 6], shape=(3,), dtype=int32)


In [67]:
tensor_2d = tf.constant([[1,5,6],[4,7,8]])
print(tensor_2d)

tf.Tensor(
[[1 5 6]
 [4 7 8]], shape=(2, 3), dtype=int32)


In [9]:
print(tensor_2d.shape)
print(tensor_2d.ndim)

(2, 3)
2


tf.dtype

In [12]:
tensor_dtype = tf.constant(1., dtype = tf.float16)
print(tensor_dtype)

tf.Tensor(1.0, shape=(), dtype=float16)


Casting

In [13]:
tensor_casted = tf.cast(tensor_dtype, dtype = tf.float64)
print(tensor_casted)

tf.Tensor(1.0, shape=(), dtype=float64)


Coverting from other structures

In [18]:
np_array = np.array([3,4,5])
tensor_from_array = tf.convert_to_tensor(np_array, dtype=tf.float16)
print(np_array)
print(tensor_from_array)

[3 4 5]
tf.Tensor([3. 4. 5.], shape=(3,), dtype=float16)


Basics

In [20]:
identity_matrix = tf.eye(5)
identity_matrix

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [22]:
identity_matrix = tf.eye(5, num_columns=6, batch_shape=[3])
identity_matrix

<tf.Tensor: shape=(3, 5, 6), dtype=float32, numpy=
array([[[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.]],

       [[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.]],

       [[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.]]], dtype=float32)>

In [24]:
filled = tf.fill([4,3], 7)
filled

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]], dtype=int32)>

In [25]:
tf.ones([4,3])

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [27]:
tf.zeros([4,3])

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [28]:
tf.ones_like(filled)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [31]:
tf.random_normal_initializer(mean=0, stddev=2)

In [33]:
tf.range(start=2, limit=10, delta=1)

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [36]:
tf.rank(filled)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [37]:
tf.shape(filled)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 3], dtype=int32)>

In [38]:
tf.size(filled)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

Rnadom

In [41]:
g = tf.random.Generator.from_non_deterministic_state()
g.normal(shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.8444182 , -0.402793  ],
       [ 0.80031186, -0.81653285]], dtype=float32)>

In [50]:
g = tf.random.Generator.from_seed(9)
g.normal(shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.6039789 , -0.1766927 ],
       [ 0.04221033,  0.29037967]], dtype=float32)>

In [52]:
g.normal(shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.00153109, -1.5086719 ],
       [-1.3783513 , -0.27838048]], dtype=float32)>

In [53]:
tf.random.normal(shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.3930306 , -0.8280769 ],
       [ 0.7576759 , -0.99691665]], dtype=float32)>

Indexing

In [54]:
tensor_indexing = tf.constant([3,4,5,6,6,7,8,8])
tensor_indexing[0:4]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 4, 5, 6], dtype=int32)>

In [55]:
tensor_indexing[...]

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([3, 4, 5, 6, 6, 7, 8, 8], dtype=int32)>

Math

In [56]:
tf.abs(tf.constant([-2,4]))

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [57]:
tf.abs(tf.constant([-2 + 4j]))

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([4.47213595])>

In [59]:
x1 = tf.constant([1,1,1,1,1])
x2 = tf.constant([1,1,1,1,1])
tf.add(x1,x2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 2, 2, 2, 2], dtype=int32)>

In [60]:
tf.multiply(x1,x2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 1, 1, 1, 1], dtype=int32)>

In [61]:
tf.subtract(x1,x2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 0, 0, 0, 0], dtype=int32)>

In [62]:
tf.divide(x1,x2)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 1., 1., 1., 1.])>

In [64]:
tf.minimum(x1,x2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 1, 1, 1, 1], dtype=int32)>

In [69]:
tf.math.argmax(tensor_2d, 1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 2])>

In [70]:
tf.math.equal(x1,x2)

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([ True,  True,  True,  True,  True])>

In [74]:
tf.math.reduce_sum(x2,axis=None) # none means all matrix

<tf.Tensor: shape=(), dtype=int32, numpy=5>

Linear Algebra

In [77]:
x_1 = tf.constant([[1,2,0],[3,5,-1]])
x_2 = tf.constant([[1,2,0],[3,5,-1],[4,5,6]])

tf.linalg.matmul(x_1, x_2, transpose_a=False,
                 transpose_b=False, adjoint_a=False,
                 adjoint_b=False, a_is_sparse=False,
                 b_is_sparse=False, output_type=None,
                 name=None)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[  7,  12,  -2],
       [ 14,  26, -11]], dtype=int32)>

In [78]:
## (lower<0 || m-n <= lower) && (upper<0 || n-m <= upper )

tf.linalg.band_part(tensor_2d,0,0)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 0, 0],
       [0, 7, 0]], dtype=int32)>

In [ ]:
# linalg.inv

In [83]:
tensor_2d = tf.cast(tensor_2d, dtype=tf.float32)
print(tensor_2d)
tf.linalg.svd(tensor_2d)

tf.Tensor(
[[1. 5. 6.]
 [4. 7. 8.]], shape=(2, 3), dtype=float32)


(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([13.737789 ,  1.5076884], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.5659777, -0.8244205],
        [-0.8244205,  0.5659777]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.2812432 ,  0.95476604],
        [-0.62607104, -0.10629445],
        [-0.7272808 , -0.27771056]], dtype=float32)>)

In [ ]:
# np.einsum