In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tensor_0d = tf.constant(1)
print(tensor_0d)

tf.Tensor(1, shape=(), dtype=int32)


In [3]:
tensor_1d = tf.constant([1,5,6])
print(tensor_1d)

tf.Tensor([1 5 6], shape=(3,), dtype=int32)


In [4]:
tensor_2d = tf.constant([[1,5,6],[4,7,8]])
print(tensor_2d)

tf.Tensor(
[[1 5 6]
 [4 7 8]], shape=(2, 3), dtype=int32)


In [5]:
print(tensor_2d.shape)
print(tensor_2d.ndim)

(2, 3)
2


tf.dtype

In [6]:
tensor_dtype = tf.constant(1., dtype = tf.float16)
print(tensor_dtype)

tf.Tensor(1.0, shape=(), dtype=float16)


Casting

In [7]:
tensor_casted = tf.cast(tensor_dtype, dtype = tf.float64)
print(tensor_casted)

tf.Tensor(1.0, shape=(), dtype=float64)


Coverting from other structures

In [8]:
np_array = np.array([3,4,5])
tensor_from_array = tf.convert_to_tensor(np_array, dtype=tf.float16)
print(np_array)
print(tensor_from_array)

[3 4 5]
tf.Tensor([3. 4. 5.], shape=(3,), dtype=float16)


Basics

In [9]:
identity_matrix = tf.eye(5)
identity_matrix

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [10]:
identity_matrix = tf.eye(5, num_columns=6, batch_shape=[3])
identity_matrix

<tf.Tensor: shape=(3, 5, 6), dtype=float32, numpy=
array([[[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.]],

       [[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.]],

       [[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.]]], dtype=float32)>

In [11]:
filled = tf.fill([4,3], 7)
filled

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]], dtype=int32)>

In [12]:
tf.ones([4,3])

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [13]:
tf.zeros([4,3])

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [14]:
tf.ones_like(filled)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [15]:
tf.random_normal_initializer(mean=0, stddev=2)

In [16]:
tf.range(start=2, limit=10, delta=1)

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [17]:
tf.rank(filled)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [18]:
tf.shape(filled)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 3], dtype=int32)>

In [19]:
tf.size(filled)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

Rnadom

In [20]:
g = tf.random.Generator.from_non_deterministic_state()
g.normal(shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.9365563 , -1.3943864 ],
       [ 0.05823072, -0.46240035]], dtype=float32)>

In [21]:
g = tf.random.Generator.from_seed(9)
g.normal(shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.6039789 , -0.1766927 ],
       [ 0.04221033,  0.29037967]], dtype=float32)>

In [22]:
g.normal(shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.1029284 , -0.14670314],
       [-1.3984425 , -1.5443149 ]], dtype=float32)>

In [23]:
tf.random.normal(shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.7785007 , -0.35676655],
       [-0.528933  ,  1.0294029 ]], dtype=float32)>

Indexing

In [24]:
tensor_indexing = tf.constant([3,4,5,6,6,7,8,8])
tensor_indexing[0:4]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 4, 5, 6], dtype=int32)>

In [25]:
tensor_indexing[...]

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([3, 4, 5, 6, 6, 7, 8, 8], dtype=int32)>

Math

In [26]:
tf.abs(tf.constant([-2,4]))

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [27]:
tf.abs(tf.constant([-2 + 4j]))

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([4.47213595])>

In [28]:
x1 = tf.constant([1,1,1,1,1])
x2 = tf.constant([1,1,1,1,1])
tf.add(x1,x2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 2, 2, 2, 2], dtype=int32)>

In [29]:
tf.multiply(x1,x2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 1, 1, 1, 1], dtype=int32)>

In [30]:
tf.subtract(x1,x2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 0, 0, 0, 0], dtype=int32)>

In [31]:
tf.divide(x1,x2)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 1., 1., 1., 1.])>

In [32]:
tf.minimum(x1,x2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 1, 1, 1, 1], dtype=int32)>

In [33]:
tf.math.argmax(tensor_2d, 1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 2])>

In [34]:
tf.math.equal(x1,x2)

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([ True,  True,  True,  True,  True])>

In [35]:
tf.math.reduce_sum(x2,axis=None) # none means all matrix

<tf.Tensor: shape=(), dtype=int32, numpy=5>

Linear Algebra

In [36]:
x_1 = tf.constant([[1,2,0],[3,5,-1]])
x_2 = tf.constant([[1,2,0],[3,5,-1],[4,5,6]])

tf.linalg.matmul(x_1, x_2, transpose_a=False,
                 transpose_b=False, adjoint_a=False,
                 adjoint_b=False, a_is_sparse=False,
                 b_is_sparse=False, output_type=None,
                 name=None)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[  7,  12,  -2],
       [ 14,  26, -11]], dtype=int32)>

In [37]:
## (lower<0 || m-n <= lower) && (upper<0 || n-m <= upper )

tf.linalg.band_part(tensor_2d,0,0)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 0, 0],
       [0, 7, 0]], dtype=int32)>

In [38]:
# linalg.inv

In [39]:
tensor_2d = tf.cast(tensor_2d, dtype=tf.float32)
print(tensor_2d)
tf.linalg.svd(tensor_2d)

tf.Tensor(
[[1. 5. 6.]
 [4. 7. 8.]], shape=(2, 3), dtype=float32)


(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([13.737789 ,  1.5076884], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.5659777, -0.8244205],
        [-0.8244205,  0.5659777]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.2812432 ,  0.95476604],
        [-0.62607104, -0.10629445],
        [-0.7272808 , -0.27771056]], dtype=float32)>)

In [40]:
# np.einsum

Ragged Tensors

In [42]:
tensor_2d = tf.constant([[1,5,6],[4,7,8]])

ragged_list = [[1,5,6],[4,8]]

tensor_ragged = tf.ragged.constant(ragged_list)
tensor_ragged.shape

TensorShape([2, None])

In [43]:
list1 = [[1,5,6],[4,7,8]]
mask = [[True,False,True],[True,True,False]]
tf.ragged.boolean_mask(list1, mask)

<tf.RaggedTensor [[1, 6],
 [4, 7]]>

In [44]:
tf.RaggedTensor.from_row_lengths(values=[1,2,3,4,5,5,6],
                                 row_lengths=[1,4,2,0])

<tf.RaggedTensor [[1], [2, 3, 4, 5], [5, 6], []]>

In [47]:
tf.RaggedTensor.from_row_limits( values=[1,2,3,4,5,5,6],
                                 row_limits=[1,4,4,6,7])

<tf.RaggedTensor [[1], [2, 3, 4], [], [5, 5], [6]]>

In [49]:
tf.RaggedTensor.from_tensor(tensor_2d,lengths=[1,2])

<tf.RaggedTensor [[1], [4, 7]]>

Sparse Tensors

In [53]:
sparse = tf.sparse.SparseTensor(
    indices = [[1,1],[3,4]], values=[11,56],dense_shape=[5,6]
)

In [54]:
tf.sparse.to_dense(sparse)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)>

String Tensors

In [55]:
tensor_string = tf.constant(["ddd","ddd"])
tensor_string

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'ddd', b'ddd'], dtype=object)>

In [56]:
tf.strings.join(tensor_string, separator=",")

<tf.Tensor: shape=(), dtype=string, numpy=b'ddd,ddd'>

In [58]:
tf.strings.length(tensor_string)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3], dtype=int32)>

Variables

In [59]:
x_var = tf.Variable(tensor_2d)
x_var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 5, 6],
       [4, 7, 8]], dtype=int32)>

In [61]:
x_var = tf.Variable([5,6])
x_var.assign_sub([1,4])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([4, 2], dtype=int32)>

In [65]:
with tf.device('CPU:0'):
  x_var1 = tf.Variable([5,6])

print(x_var1.device)

with tf.device('GPU:0'):
  x_var2 = tf.Variable([5,6])

print(x_var2.device)

/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:CPU:0
